### ISSUE TITLE
[BUG] Fails to build with libavcodec 7.1.1

### ISSUE THREAD

**Issue by mz-pdm** [raspberrypi/rpicam-apps#797]
When I try to build the apps on Fedora rawhide, I get the following compilation error:

```
c++ -Irpicam_app.so.1.6.0.p -I. -I.. -I/usr/include/libcamera -I/usr/include -I/usr/include/ffmpeg -I/usr/include/webp -I/usr/include/libpng16 -I/usr/include/libdrm -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c++17 -O3 -pedantic -Wno-unused-parameter -faligned-new -D_FILE_OFFSET_BITS=64 -Wno-psabi -DLIBAV_PRESENT=1 -DLIBDRM_PRESENT=1 -DLIBEGL_PRESENT=1 -fPIC -DWITH_GZFILEOP -pthread -DBOOST_ALL_NO_LIB -MD -MQ rpicam_app.so.1.6.0.p/encoder_libav_encoder.cpp.o -MF rpicam_app.so.1.6.0.p/encoder_libav_encoder.cpp.o.d -o rpicam_app.so.1.6.0.p/encoder_libav_encoder.cpp.o -c ../encoder/libav_encoder.cpp
../encoder/libav_encoder.cpp: In member function ‘void LibAvEncoder::initAudioOutCodec(const VideoOptions*, const StreamInfo&)’:
../encoder/libav_encoder.cpp:322:51: error: ‘AVCodec::sample_fmts’ is deprecated [-Werror=deprecated-declarations]
  322 |         codec_ctx_[AudioOut]->sample_fmt = codec->sample_fmts[0];
      |                                                   ^~~~~~~~~~~
In file included from /usr/include/ffmpeg/libavcodec/avcodec.h:41,
                 from ../encoder/libav_encoder.hpp:19,
                 from ../encoder/libav_encoder.cpp:20:
/usr/include/ffmpeg/libavcodec/codec.h:219:32: note: declared here
  219 |     const enum AVSampleFormat *sample_fmts; ///< @deprecated use avcodec_get_supported_config()
      |                                ^~~~~~~~~~~
```

This can be avoided by passing `-Dwerror=false` to meson but the default compilation shouldn't fail.

**Comment by naushir** [comment]
I'll look to change https://github.com/raspberrypi/rpicam-apps/pull/792 to add an ``#ifdef`` so that it can compile with older versions of ffmpeg like what we currently use.

**Comment by naushir** [comment]
https://github.com/raspberrypi/rpicam-apps/pull/800 adds and #ifdef that will conditionally compile this with our existing ffmpeg version on Raspberry Pi OS.
