### ISSUE TITLE
Build fails against libcamera 0.5 due to missing SyncMode

### ISSUE THREAD

**Issue by strophy** [raspberrypi/rpicam-apps#798]
**Description**
I'm trying to package rpicam-apps v1.6.0 for Alpine Linux. Build fails against libcamera 0.5.0 due to missing `SyncMode` and `AeLocked` in a way that looks very similar to #774 and https://github.com/raspberrypi/libcamera/issues/246

**To Reproduce**
Run `abuild` against this [APKBUILD](https://gitlab.alpinelinux.org/strophy/aports/-/blob/libcamera-0.5/testing/rpicam-apps/APKBUILD) file, errors with:
```
>>> rpicam-apps: Unpacking /var/cache/distfiles/rpicam-apps-v1.6.0.tar.gz...
The Meson build system
Version: 1.6.1
Source dir: /builds/strophy/aports/testing/rpicam-apps/src/rpicam-apps-1.6.0
Build dir: /builds/strophy/aports/testing/rpicam-apps/src/rpicam-apps-1.6.0/build
Build type: native build
Project name: rpicam-apps
Project version: 1.6.0
C compiler for the host machine: cc (gcc 14.2.0 "cc (Alpine 14.2.0) 14.2.0")
C linker for the host machine: cc ld.bfd 2.44
C++ compiler for the host machine: c++ (gcc 14.2.0 "c++ (Alpine 14.2.0) 14.2.0")
C++ linker for the host machine: c++ ld.bfd 2.44
Host machine cpu family: aarch64
Host machine cpu: aarch64
Run-time dependency dl found: YES
Found pkg-config: YES (/usr/bin/pkg-config) 2.4.3
Run-time dependency libcamera found: YES 0.5.0
Run-time dependency Boost (found: program_options) found: YES 1.84.0 (/usr)
Run-time dependency threads found: YES
Run-time dependency libavcodec found: YES 60.31.102
Run-time dependency libavdevice found: YES 60.3.100
Run-time dependency libavformat found: YES 60.16.100
Run-time dependency libavutil found: YES 58.29.100
Run-time dependency libswresample found: YES 4.12.100
Run-time dependency libexif found: YES 0.6.25
Run-time dependency libjpeg found: YES 3.1.0
Run-time dependency libtiff-4 found: YES 4.7.0
Run-time dependency libpng found: YES 1.6.47
Run-time dependency libdrm found: YES 2.4.124
Dependency x11 skipped: feature enable_egl disabled
Dependency epoxy skipped: feature enable_egl disabled
Dependency qt5 (modules: Core, Widgets) skipped: feature enable_qt disabled
Configuring postproc_lib.h using configuration
Dependency opencv4 skipped: feature enable_opencv disabled
Dependency tensorflow-lite skipped: feature enable_tflite disabled
Dependency HailoRT (modules: HailoRT::libhailort) skipped: feature enable_hailo disabled
Dependency hailo-tappas-core skipped: feature enable_hailo disabled
Build targets in project: 8
rpicam-apps 1.6.0
  libcamera
    location             : /usr/lib
    version              : 0.5.0
  Build configuration
    libav encoder        : YES
    drm preview          : YES
    egl preview          : NO
    qt preview           : NO
    OpenCV postprocessing: NO
    TFLite postprocessing: NO
    Hailo postprocessing : NO
    IMX500 postprocessing: NO
  User defined options
    auto_features        : auto
    b_lto                : false
    b_pie                : true
    b_staticpic          : true
    bindir               : /usr/bin
    buildtype            : plain
    datadir              : /usr/share
    download_hailo_models: false
    enable_drm           : enabled
    enable_egl           : disabled
    enable_hailo         : disabled
    enable_libav         : enabled
    enable_opencv        : disabled
    enable_qt            : disabled
    enable_tflite        : disabled
    includedir           : /usr/include
    infodir              : /usr/share/info
    libdir               : /usr/lib
    libexecdir           : /usr/libexec
    localedir            : /usr/share/locale
    localstatedir        : /var
    mandir               : /usr/share/man
    neon_flags           : auto
    prefix               : /usr
    python.bytecompile   : 0
    sbindir              : /usr/sbin
    sharedstatedir       : /var/lib
    sysconfdir           : /etc
    werror               : false
    wrap_mode            : nodownload
Found ninja-1.9 at /usr/bin/ninja
ninja: entering directory '/builds/strophy/aports/testing/rpicam-apps/src/rpicam-apps-1.6.0/build'
[1/43] Compiling C++ object apps/rpicam-jpeg.p/rpicam_jpeg.cpp.o
[2/43] Compiling C++ object apps/rpicam-raw.p/rpicam_raw.cpp.o
[3/43] Compiling C++ object apps/rpicam-hello.p/rpicam_hello.cpp.o
[4/43] Compiling C++ object apps/rpicam-vid.p/rpicam_vid.cpp.o
[5/43] Compiling C++ object apps/rpicam-still.p/rpicam_still.cpp.o
[6/43] Compiling C++ object rpicam_app.so.1.6.0.p/post_processing_stages_pwl.cpp.o
[7/43] Compiling C++ object rpicam_app.so.1.6.0.p/post_processing_stages_post_processing_stage.cpp.o
[8/43] Compiling C++ object rpicam_app.so.1.6.0.p/post_processing_stages_histogram.cpp.o
[9/43] Compiling C++ object rpicam_app.so.1.6.0.p/preview_drm_preview.cpp.o
[10/43] Compiling C++ object rpicam_app.so.1.6.0.p/preview_preview.cpp.o
[11/43] Compiling C++ object rpicam_app.so.1.6.0.p/preview_null_preview.cpp.o
[12/43] Compiling C++ object rpicam_app.so.1.6.0.p/output_output.cpp.o
[13/43] Compiling C++ object rpicam_app.so.1.6.0.p/output_net_output.cpp.o
[14/43] Compiling C++ object rpicam_app.so.1.6.0.p/output_file_output.cpp.o
[15/43] Compiling C++ object rpicam_app.so.1.6.0.p/output_circular_output.cpp.o
[16/43] Compiling C++ object rpicam_app.so.1.6.0.p/image_yuv.cpp.o
[17/43] Compiling C++ object rpicam_app.so.1.6.0.p/image_png.cpp.o
[18/43] Compiling C++ object rpicam_app.so.1.6.0.p/image_jpeg.cpp.o
[19/43] Compiling C++ object rpicam_app.so.1.6.0.p/image_dng.cpp.o
[20/43] Compiling C++ object rpicam_app.so.1.6.0.p/image_bmp.cpp.o
[21/43] Compiling C++ object rpicam_app.so.1.6.0.p/encoder_libav_encoder.cpp.o
[22/43] Compiling C++ object rpicam_app.so.1.6.0.p/encoder_null_encoder.cpp.o
[23/43] Compiling C++ object rpicam_app.so.1.6.0.p/encoder_mjpeg_encoder.cpp.o
[24/43] Compiling C++ object rpicam_app.so.1.6.0.p/encoder_h264_encoder.cpp.o
[25/43] Compiling C++ object rpicam_app.so.1.6.0.p/encoder_encoder.cpp.o
[26/43] Compiling C++ object rpicam_app.so.1.6.0.p/core_post_processor.cpp.o
[27/43] Compiling C++ object rpicam_app.so.1.6.0.p/core_options.cpp.o
[28/43] Compiling C++ object rpicam_app.so.1.6.0.p/core_rpicam_app.cpp.o
[29/43] Compiling C++ object rpicam_app.so.1.6.0.p/core_dma_heaps.cpp.o
[30/43] Compiling C++ object rpicam_app.so.1.6.0.p/core_buffer_sync.cpp.o
[31/43] Generating version.cpp with a custom command
[32/43] Compiling C++ object post_processing_stages/core-postproc.so.p/negate_stage.cpp.o
[33/43] Compiling C++ object post_processing_stages/core-postproc.so.p/motion_detect_stage.cpp.o
ERR: Invalid git directory!
[34/43] Compiling C++ object rpicam_app.so.1.6.0.p/meson-generated_.._version.cpp.o
[35/43] Compiling C++ object post_processing_stages/core-postproc.so.p/hdr_stage.cpp.o
ninja: job failed: c++ -Iapps/rpicam-vid.p -Iapps -I../apps -I. -I.. -I/usr/include/libcamera -I/usr/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -pedantic -Wno-unused-parameter -faligned-new -D_FILE_OFFSET_BITS=64 -Wno-psabi -ftree-vectorize -DLIBAV_PRESENT=1 -DLIBDRM_PRESENT=1 -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fPIE -DBOOST_ALL_NO_LIB -MD -MQ apps/rpicam-vid.p/rpicam_vid.cpp.o -MF apps/rpicam-vid.p/rpicam_vid.cpp.o.d -o apps/rpicam-vid.p/rpicam_vid.cpp.o -c ../apps/rpicam_vid.cpp
In file included from ../apps/rpicam_vid.cpp:14:
../core/rpicam_encoder.hpp: In member function 'void RPiCamEncoder::StartEncoder()':
../core/rpicam_encoder.hpp:38:58: error: 'SyncMode' is not a member of 'libcamera::controls::rpi'
   38 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeOff);
      |                                                          ^~~~~~~~
../core/rpicam_encoder.hpp:38:94: error: 'SyncModeOff' is not a member of 'libcamera::controls::rpi'
   38 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeOff);
      |                                                                                              ^~~~~~~~~~~
../core/rpicam_encoder.hpp:40:58: error: 'SyncMode' is not a member of 'libcamera::controls::rpi'
   40 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeServer);
      |                                                          ^~~~~~~~
../core/rpicam_encoder.hpp:40:94: error: 'SyncModeServer' is not a member of 'libcamera::controls::rpi'
   40 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeServer);
      |                                                                                              ^~~~~~~~~~~~~~
../core/rpicam_encoder.hpp:42:58: error: 'SyncMode' is not a member of 'libcamera::controls::rpi'
   42 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeClient);
      |                                                          ^~~~~~~~
../core/rpicam_encoder.hpp:42:94: error: 'SyncModeClient' is not a member of 'libcamera::controls::rpi'
   42 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeClient);
      |                                                                                              ^~~~~~~~~~~~~~
../core/rpicam_encoder.hpp: In member function 'void RPiCamEncoder::EncodeBuffer(CompletedRequestPtr&, Stream*)':
../core/rpicam_encoder.hpp:53:91: error: 'SyncReady' is not a member of 'libcamera::controls::rpi'
   53 |                 if (GetOptions()->sync && !completed_request->metadata.get(controls::rpi::SyncReady).value_or(false))
      |                                                                                           ^~~~~~~~~
ninja: job failed: c++ -Iapps/rpicam-still.p -Iapps -I../apps -I. -I.. -I/usr/include/libcamera -I/usr/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -pedantic -Wno-unused-parameter -faligned-new -D_FILE_OFFSET_BITS=64 -Wno-psabi -ftree-vectorize -DLIBAV_PRESENT=1 -DLIBDRM_PRESENT=1 -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fPIE -DBOOST_ALL_NO_LIB -MD -MQ apps/rpicam-still.p/rpicam_still.cpp.o -MF apps/rpicam-still.p/rpicam_still.cpp.o.d -o apps/rpicam-still.p/rpicam_still.cpp.o -c ../apps/rpicam_still.cpp
In file included from ../apps/rpicam_still.cpp:16:
../core/frame_info.hpp: In constructor 'FrameInfo::FrameInfo(const CompletedRequestPtr&)':
../core/frame_info.hpp:50:58: error: 'AeLocked' is not a member of 'libcamera::controls'; did you mean 'AwbLocked'?
   50 |                 auto ae = ctrls.get(libcamera::controls::AeLocked);
      |                                                          ^~~~~~~~
      |                                                          AwbLocked
ninja: job failed: c++ -Iapps/rpicam-raw.p -Iapps -I../apps -I. -I.. -I/usr/include/libcamera -I/usr/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -pedantic -Wno-unused-parameter -faligned-new -D_FILE_OFFSET_BITS=64 -Wno-psabi -ftree-vectorize -DLIBAV_PRESENT=1 -DLIBDRM_PRESENT=1 -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fPIE -DBOOST_ALL_NO_LIB -MD -MQ apps/rpicam-raw.p/rpicam_raw.cpp.o -MF apps/rpicam-raw.p/rpicam_raw.cpp.o.d -o apps/rpicam-raw.p/rpicam_raw.cpp.o -c ../apps/rpicam_raw.cpp
In file included from ../apps/rpicam_raw.cpp:10:
../core/rpicam_encoder.hpp: In member function 'void RPiCamEncoder::StartEncoder()':
../core/rpicam_encoder.hpp:38:58: error: 'SyncMode' is not a member of 'libcamera::controls::rpi'
   38 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeOff);
      |                                                          ^~~~~~~~
../core/rpicam_encoder.hpp:38:94: error: 'SyncModeOff' is not a member of 'libcamera::controls::rpi'
   38 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeOff);
      |                                                                                              ^~~~~~~~~~~
../core/rpicam_encoder.hpp:40:58: error: 'SyncMode' is not a member of 'libcamera::controls::rpi'
   40 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeServer);
      |                                                          ^~~~~~~~
../core/rpicam_encoder.hpp:40:94: error: 'SyncModeServer' is not a member of 'libcamera::controls::rpi'
   40 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeServer);
      |                                                                                              ^~~~~~~~~~~~~~
../core/rpicam_encoder.hpp:42:58: error: 'SyncMode' is not a member of 'libcamera::controls::rpi'
   42 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeClient);
      |                                                          ^~~~~~~~
../core/rpicam_encoder.hpp:42:94: error: 'SyncModeClient' is not a member of 'libcamera::controls::rpi'
   42 |                         cl.set(libcamera::controls::rpi::SyncMode, libcamera::controls::rpi::SyncModeClient);
      |                                                                                              ^~~~~~~~~~~~~~
../core/rpicam_encoder.hpp: In member function 'void RPiCamEncoder::EncodeBuffer(CompletedRequestPtr&, Stream*)':
../core/rpicam_encoder.hpp:53:91: error: 'SyncReady' is not a member of 'libcamera::controls::rpi'
   53 |                 if (GetOptions()->sync && !completed_request->metadata.get(controls::rpi::SyncReady).value_or(false))
      |                                                                                           ^~~~~~~~~
../core/dma_heaps.cpp: In member function 'libcamera::UniqueFD DmaHeap::alloc(const char*, std::size_t) const':
../core/dma_heaps.cpp:68:45: warning: overflow in conversion from 'long unsigned int' to 'int' changes value from '3222816768' to '-1072150528' [-Woverflow]
   68 |         ret = ::ioctl(dmaHeapHandle_.get(), DMA_HEAP_IOCTL_ALLOC, &alloc);
      |                                             ^~~~~~~~~~~~~~~~~~~~
ninja: job failed: c++ -Irpicam_app.so.1.6.0.p -I. -I.. -I/usr/include/libcamera -I/usr/include -I/usr/include/webp -I/usr/include/libpng16 -I/usr/include/libdrm -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++17 -pedantic -Wno-unused-parameter -faligned-new -D_FILE_OFFSET_BITS=64 -Wno-psabi -ftree-vectorize -DLIBAV_PRESENT=1 -DLIBDRM_PRESENT=1 -Os -fstack-clash-protection -Wformat -Werror=format-security -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_ENABLE_HARDENED_MODE=1 -fPIC -pthread -DBOOST_ALL_NO_LIB -MD -MQ rpicam_app.so.1.6.0.p/core_rpicam_app.cpp.o -MF rpicam_app.so.1.6.0.p/core_rpicam_app.cpp.o.d -o rpicam_app.so.1.6.0.p/core_rpicam_app.cpp.o -c ../core/rpicam_app.cpp
In file included from ../core/rpicam_app.cpp:10:
../core/frame_info.hpp: In constructor 'FrameInfo::FrameInfo(const CompletedRequestPtr&)':
../core/frame_info.hpp:50:58: error: 'AeLocked' is not a member of 'libcamera::controls'; did you mean 'AwbLocked'?
   50 |                 auto ae = ctrls.get(libcamera::controls::AeLocked);
      |                                                          ^~~~~~~~
      |                                                          AwbLocked
ninja: subcommands failed
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /builds/strophy/aports/testing/rpicam-apps/src/rpicam-apps-1.6.0/build
>>> ERROR: rpicam-apps: build failed
```
Full build log is [here](https://gitlab.alpinelinux.org/strophy/aports/-/jobs/1812257).

I noticed in #774 that the recommendation was to use latest libcamera from https://github.com/raspberrypi/libcamera but the latest tag there is 0.4.0 and Alpine builds with 0.5.0 from https://gitlab.freedesktop.org/camera/libcamera/-/archive/v0.5.0/libcamera-v0.5.0.tar.gz is this correct? What is the relationship between the two repos?

**Comment by strophy** [comment]
Hi @naushir libcamera 0.5.1 was [released](https://gitlab.freedesktop.org/camera/libcamera/-/releases/v0.5.1) upstream but the error around `AeLocked` remains.

The fact that these two repos have similar/identical tags but different contents is super confusing for distro package managers, what is the relationship between the two repos? Should I be asking here or on Freedesktop GitLab for progress on merging the changes from `raspberrypi/libcamera`, whose responsibility is it to merge these changes upstream? Can I do it myself? Why not just work on a single git repo, instead of having two repos with the same name, but different contents?

**Comment by kbingham** [comment]
Oh - I thought we'd had agreement on the sync controls in the RPi namespace, I hadn't realised they were still blocked. I'll chase that later today.

**Comment by strophy** [comment]
@naushir thanks for the detailed response, I really appreciate it! And also happy to see it's on @kbingham's radar now.

Thanks for clarifying the purpose of the raspberrypi/libcamera repo, I appreciate the need for a separate repo under your direct control in order to have working camera features on the day RPi hardware is released. And I think your suggestion for a meson option makes sense, at least as a good hedge against repeating the issue in the future.

My reason for wanting to fix the (currently broken) rpicam-apps apk on Alpine is that we use Alpine-based containers on RPi CM4 boards in machinery to operate cameras and do some image processing, so for consistency reasons in our tooling it's not practical to run Raspberry Pi OS containers just to ensure working rpicam-apps. 

Thanks all for the rapid progress you're making, and for responding so quickly!
